/** 레이아웃 - UI요소 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {/* Layout UI */}
        <div className="root-layout">{children}</div>
      </body>
    </html>
  );
}
